<?xml version="1.0"?>
<package format="3">
  <name>campus_robot_navigation</name>
  <version>0.1.0</version>
  <description>Nav2 configuration and planning experiments.</description>
  <maintainer email="nexus@paichai.ac.kr">PAICHAI NEXUS</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
</package>
